if (is_ios) {
  import("//build/config/ios/ios_sdk.gni")
  import("//build/config/ios/rules.gni")
}
if (is_mac) {
  import("//build/config/mac/rules.gni")
}

config("mov_public_config") {
  include_dirs = ["include"]
}

config("mov_config") {
  cflags = [
    "-Wno-unused-but-set-variable",
    "-Wno-unused-variable",
    "-Wno-sign-compare",
    "-Wno-misleading-indentation",
    #"-Wno-error"
  ]
}

static_library("libmov") {
  public_configs = [ ":mov_public_config" ]
  configs += [ ":mov_config" ]
  sources = [
    "include/fmp4-writer.h",
    "include/mov-buffer.h",
    "include/mov-format.h",
    "include/mov-reader.h",
    "include/mov-writer.h",
    "include/mp4-writer.h",
    "source/fmp4-reader.c",
    "source/fmp4-writer.c",
    "source/mov-avc1.c",
    "source/mov-dinf.c",
    "source/mov-elst.c",
    "source/mov-esds.c",
    "source/mov-ftyp.c",
    "source/mov-hdr.c",
    "source/mov-hdlr.c",
    "source/mov-iods.c",
    "source/mov-leva.c",
    "source/mov-mdhd.c",
    "source/mov-mehd.c",
    "source/mov-mfhd.c",
    "source/mov-minf.c",
    "source/mov-mvhd.c",
    "source/mov-opus.c",
    "source/mov-reader.c",
    "source/mov-sidx.c",
    "source/mov-stco.c",
    "source/mov-stsc.c",
    "source/mov-stsd.c",
    "source/mov-stss.c",
    "source/mov-stsz.c",
    "source/mov-stts.c",
    "source/mov-tag.c",
    "source/mov-tfdt.c",
    "source/mov-tfhd.c",
    "source/mov-tfra.c",
    "source/mov-tkhd.c",
    "source/mov-track.c",
    "source/mov-trex.c",
    "source/mov-trun.c",
    "source/mov-tx3g.c",
    "source/mov-udta.c",
    "source/mov-vpcc.c",
    "source/mov-writer.c",
  ]
}